const ChatActionTypes = {
  CHAT_LIST_RETURNED: 'CHAT_LIST_RETURNED',
  CHAT_CONVERSATION_RETURNED: 'CHAT_CONVERSATION_RETURNED',
  LATEST_MESSAGE_RETURNED: 'LATEST_MESSAGE_RETURNED',
  CONVERSATION_EMPTIED: 'CONVERSATION_EMPTIED'
};

export default ChatActionTypes;
