const AppActionTypes = {
  ERROR_OCCURED: 'ERROR_OCCURED',
  CLEAR_STATUS: 'CLEAR_STATUS',

  REGISTERED: 'REGISTER',
  REGISTRATION_SUCCESSFUL: 'REGISTRATION_SUCCESSFUL',
  QR_CODE_RETURNED: 'QR_CODE_RETURNED',
  TWO_FACTOR_ENABLED: 'TWO_FACTOR_ENABLED',
  TWO_FACTOR_DISABLED: 'TWO_FACTOR_DISABLED',

  ACTIVATE_EMAIL_REQUESTED: 'ACTIVATE_EMAIL_REQUESTED',
  PASSWORD_RESET_EMAIL_REQUESTED: 'PASSWORD_RESET_EMAIL_REQUESTED',
  FORGOT_PASSWORD_RESET: 'FORGOT_PASSWORD_RESET',

  PASSWORD_RESET: 'PASSWORD_RESET',

  TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU'
};

export default AppActionTypes;
