const AccountActionTypes = {
  CONTACT_DETAILS_RETURNED: 'CONTACT_DETAILS_RETURNED',
  NOTIFICATION_SETTINGS_CHANGED: 'NOTIFICATION_SETTINGS_CHANGED',
  VERIFICATION_CODE_SENT: 'VERIFICATION_CODE_SENT',
  VERIFY_PHONE_NUMBER: 'VERIFY_PHONE_NUMBER',
  PHONE_NUMBER_SUBMITTED: 'PHONE_NUMBER_SUBMITTED',
  PHONE_NUMBER_DELETED: 'PHONE_NUMBER_DELETED',

  GET_USER: 'GET_USER',
  GENERAL_INFO_SAVED: 'GENERAL_INFO_SAVED',
  PROFILE_PIC_REMOVED: 'PROFILE_PIC_REMOVED',

  GET_SITTER_ACCOUNT: 'GET_SITTER_ACCOUNT',
  SITTER_ACCOUNT_SAVED: 'SITTER_ACCOUNT_SAVED',

  GET_OWNER_ACCOUNT: 'GET_OWNER_ACCOUNT',
  OWNER_ACCOUNT_SAVED: 'OWNER_ACCOUNT_SAVED',
  CAT_PIC_REMOVED: 'CAT_PIC_REMOVED'
};

export default AccountActionTypes;
