const BookingsActionTypes = {
  OWNER_PROFILE_NOT_FOUND: 'OWNER_PROFILE_NOT_FOUND',
  APPOINTMENT_TIME_NOT_FOUND: 'APPOINTMENT_TIME_NOT_FOUND',
  APPOINTMENT_TIME_RETURNED: 'APPOINTMENT_TIME_RETURNED',

  BOOKING_REQUEST_SENT: 'BOOKING_REQUEST_SENT',
  BOOKING_RECORDS_RETURNED: 'BOOKING_RECORDS_RETURNED',

  ACTION_FULFILLED: 'ACTION_FULFILLED',
  REVIEW_SUBMITTED: 'REVIEW_SUBMITTED'
};

export default BookingsActionTypes;
