const AuthActionTypes = {
  ERROR_OCCURED: 'ERROR_OCCURED',
  ACCESS_TOKEN_ATTAINED: 'ACCESS_TOKEN_ATTAINED',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  GOOGLE_LOGIN: 'GOOGLE_LOGIN',
  GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
  PHONE_LOGIN: 'PHONE_LOGIN',

  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  ACTIVATION_SUCCESS: 'ACTIVATION_SUCCESS',
  ACTIVATION_FAILED: 'ACTIVATION_FAILED',
};

export default AuthActionTypes;
