const ERROR = {
  EMAIL_ALREADY_EXISTS: 'ERROR/EMAIL_ALREADY_EXISTS',
  LOGIN_FAILED: 'ERROR/LOGIN_FAILED',
  LOGIN_CREDENTIALS_INVALID: 'ERROR/LOGIN_CREDENTIALS_INVALID',
  PHONE_VERIFICATION_FAILED: 'ERROR/PHONE_VERIFICATION_FAILED',
  PHONE_SAVING_FAILED: 'ERROR/PHONE_SAVING_FAILED',
  PHONE_ALREADY_EXISTS: 'ERROR/PHONE_ALREADY_EXISTS',
  PHONE_SUBMISSION_FAILED: 'ERROR/PHONE_SUBMISSION_FAILED',
  PASSOWORD_RESET_FAILED: 'ERROR/PASSOWORD_RESET_FAILED',
  OTP_EXPIRED: 'ERROR/OTP_EXPIRED',
  OTP_INVALID: 'ERROR/OTP_INVALID',
  GOOGLE_OTP_INVALID: 'ERROR/GOOGLE_OTP_INVALID',
  TWO_FACTOR_ACTIVATION_FAILED: 'ERROR/TWO_FACTOR_ACTIVATION_FAILED',
  PASSWORD_INCORRECT: 'ERROR/PASSWORD_INCORRECT',
  SET_EMAIL_NOTIFICATION_FAILED: 'ERROR/SET_EMAIL_NOTIFICATION_FAILED',
  SET_PHONE_NOTIFICATION_FAILED: 'ERROR/SET_PHONE_NOTIFICATION_FAILED'
}

export default ERROR;