const LoadingTypes = {
  CLEAR_LOADING: 'CLEAR_LOADING',

  ACCOUNT_LOADING: 'ACCOUNT_LOADING',
  APP_LOADING: 'APP_LOADING',
  AUTHENTICATION_LOADING: 'AUTHENTICATION_LOADING',
  BOOKINGS_LOADING: 'BOOKINGS_LOADING',
  CHAT_LOADING: 'CHAT_LOADING',
  FIND_CAT_SITTER_LOADING: 'FIND_CAT_SITTER_LOADING',
  PAYMENT_LOADING: 'PAYMENT_LOADING',
  PROFILE_LOADING: 'PROFILE_LOADING'
};

export default LoadingTypes;
