const LoadingActionTypes = {
  CLEAR_LOADING: 'CLEAR_LOADING',

  SET_ACCOUNT_LOADING: 'SET_ACCOUNT_LOADING',
  SET_APP_LOADING: 'SET_APP_LOADING',
  SET_AUTH_LOADING: 'SET_AUTH_LOADING',
  SET_BOOKINGS_LOADING: 'SET_BOOKINGS_LOADING',
  SET_CHAT_LOADING: 'SET_CHAT_LOADING',
  SET_FIND_SITTER_LOADING: 'SET_FIND_SITTER_LOADING',
  SET_PAYMENT_LOADING: 'SET_PAYMENT_LOADING',
  SET_PROFILE_LOADING: 'SET_PROFILE_LOADING'
};

export default LoadingActionTypes;
