const NotificationsActionTypes = {
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  UPDATE_BOOKING_NOTIFICATIONS: ' UPDATE_BOOKING_NOTIFICATIONS',
  UPDATE_CHAT_NOTIFICATIONS: ' UPDATE_CHAT_NOTIFICATIONS'
}

export default NotificationsActionTypes;