const NotificationsActionTypes = {
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  SET_READ_AS_OWNER: 'SET_READ_AS_OWNER',
  SET_READ_AS_SITTER: 'SET_READ_AS_SITTER',
  SET_ALL_BOOKINGS_AS_READ: 'SET_ALL_BOOKINGS_AS_READ',
  UPDATE_CHAT_NOTIFICATIONS: ' UPDATE_CHAT_NOTIFICATIONS'
}

export default NotificationsActionTypes;