const ErrorActionTypes = {
  CLEAR_ERROR: 'CLEAR_ERROR',
  CLEAR_ALL_ERRORS: 'CLEAR_ALL_ERRORS',

  SET_ACCOUNT_ERROR: 'SET_ACCOUNT_ERROR',
  SET_APP_ERROR: 'SET_APP_ERROR',
  SET_AUTH_ERROR: 'SET_AUTH_ERROR',
  SET_BOOKINGS_ERROR: 'SET_BOOKINGS_ERROR',
  SET_CHAT_ERROR: 'SET_CHAT_ERROR',
  SET_FIND_SITTER_ERROR: 'SET_FIND_SITTER_ERROR',
  SET_PAYMENT_ERROR: 'SET_PAYMENT_ERROR',
  SET_PROFILE_ERROR: 'SET_PROFILE_ERROR'
};

export default ErrorActionTypes;
