const ErrorTypes = {
  CLEAR_ERROR: 'CLEAR_ERROR',

  ACCOUNT_ERROR: 'ACCOUNT_ERROR',
  APP_ERROR: 'APP_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  BOOKINGS_ERROR: 'BOOKINGS_ERROR',
  CHAT_ERROR: 'CHAT_ERROR',
  FIND_CAT_SITTER_ERROR: 'FIND_CAT_SITTER_ERROR',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  PROFILE_ERROR: 'PROFILE_ERROR'
};

export default ErrorTypes;
